### ISSUE TITLE
Please specify author 'email' in the application package.json

### ISSUE THREAD

**Issue by probonopd** [cafeparadox/laser#1]
Error: Please specify author 'email' in the application package.json.

See https://docs.npmjs.com/files/package.json#people-fields-author-contributors

It is required to set Linux .deb package maintainer. Or you can set maintainer in the custom linux options (see https://github.com/electron-userland/electron-builder#distributable-format-configuration).

**Comment by sonnyg** [comment]
Used shortened form to specify author email.

**Comment by khurana3192** [comment]
Sorry for sounding noob, but can you please tell me what is shortened form of an email

**Comment by murilobr** [comment]
@khurana3192 
https://docs.npmjs.com/files/package.json#people-fields-author-contributors

**Comment by sonnyg** [comment]
Thanks @murilobr

**Comment by ghafran** [comment]
Please use `"author": "John Doe <john@doe.com>"`

**Comment by sonnyg** [comment]
For the record, there are two package.json files for this particular project, as originally recommended by the electron-builder utility. They have since moved on to using a single package.json file and if/when I ever get back to this project, I'll move to a single package.json file as well.
